Migrations-1223 - Improve Documentation
opensearch-project/opensearch-migrations pull request #242
Opened 2023-07-25 22:09 UTC by okhasawn

### Description
This PR enhances the current documentation/readme files in the repo.

### Issues Resolved
[Migrations-1223](https://opensearch.atlassian.net/browse/MIGRATIONS-1223)

### Check List
- [ ] New functionality includes testing
  - [ ] All tests pass, including unit test, integration test and doctest
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-26 12:24 UTC, sumobrian requested changes
Maybe I'm missing it but I don't see documentation on "running the tools." I would add information about the OpenSearch benchmark container, provide an example run, and reference the OpenSearch benchmark documentation. 

Documenting how data flows from OpenSearch benchmarks to the replayer would be ideal. Keep in mind that the replayer responses are going to be stored in persistent storage. I would reference this but leave further documentation about the Comparator out. 

Can you open another task specifically for documenting how to analyze output? Also another task for cleanup if it doesn't exist?

2023-07-26 12:24 UTC, sumobrian commented on README.md
> +Developers must run the "install_githooks.sh" script in order to add the pre-commit hook, which runs a linting command
Change "the pre-commit hook" to "any pre-commit hooks"

2023-07-26 12:24 UTC, sumobrian commented on README.md
>  The TrafficCapture directory hosts a set of projects designed to facilitate the proxying and capturing of HTTP
Replace HTTP with HTTP(S)

2023-07-26 12:24 UTC, sumobrian commented on README.md
> +This repo will contain code, tools and documentation to assist in migrations to and upgrades of OpenSearch clusters.
Change "This repo will contain code" to "This repo contains code"

2023-07-26 12:24 UTC, sumobrian commented on TrafficCapture/dockerSolution/README.md
> +depending on which tool/project is being built. The below example shows the error printed when running e.g `./gradlew
"The below example shows the error printed when running"

-->
Below is an example error when attempting to build with an incompatible Java version.

2023-07-26 12:24 UTC, sumobrian commented on TrafficCapture/dockerSolution/README.md
> +Must have Java version 11 installed.
I would remove this sentence and leave the one below.

2023-07-26 12:24 UTC, sumobrian commented on test/README.md
> +#### Pre-requisites
Spacing?

2023-07-26 12:24 UTC, sumobrian commented on test/README.md
> +pip install -r requirements.txt
Python version should also be called out above under compatability.

2023-07-26 15:02 UTC, okhasawn commented
> Maybe I'm missing it but I don't see documentation on "running the tools." I would add information about the OpenSearch benchmark container, provide an example run, and reference the OpenSearch benchmark documentation.
> 
> Documenting how data flows from OpenSearch benchmarks to the replayer would be ideal. Keep in mind that the replayer responses are going to be stored in persistent storage. I would reference this but leave further documentation about the Comparator out.
> 
> Can you open another task specifically for documenting how to analyze output? Also another task for cleanup if it doesn't exist?

@sumobrian, What I had in mind around "running the tools" was the already existing documentation on how to stand up the Docker Solution and/or the current AWS Deployment. But documentation around the OpenSearch benchmark is still needed and is a great idea! Thanks for pointing that out! I'll address that.

Created the linked tasks below:
- Cleanup: https://opensearch.atlassian.net/browse/MIGRATIONS-1270
- Analyze Output: https://opensearch.atlassian.net/browse/MIGRATIONS-1271

2023-07-31 03:29 UTC, sumobrian approved these changes

2023-07-31 03:29 UTC, merged