Removing open search analytics cluster
opensearch-project/opensearch-migrations pull request #515
Opened 2024-02-20 13:35 UTC by gregschohn

### Description

Kill the OpenSearch analytics domain and its bastion host that came along with the otel-collector, leaving only the collector (which will shoot metrics and traces to AWS).
I've also updated the README and have made the cdk.context.json set otelCollectorEnabled = true, though maybe the default should be true & this should be opt-out.

* Category Maintenance?
* Why these changes are required? The OpenSearch analytics domain and the metrics that it was tracking are obviated by the cloudwatch metrics that the otel-collector is now sending out.
* What is the old behavior before changes and new behavior after changes? CDK will no longer deploy an extra domain and bastion.

### Issues Resolved
https://opensearch.atlassian.net/browse/MIGRATIONS-1475

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-20 21:25 UTC, AndreKurait commented
is something weird with the commit history here? All my commits are showing up as unverified

2024-02-21 14:41 UTC, AndreKurait commented on TrafficCapture/dockerSolution/src/main/docker/otelCollector/Dockerfile
> +FROM public.ecr.aws/aws-observability/aws-otel-collector:v0.37.0
Thank for this

2024-02-21 14:57 UTC, AndreKurait approved these changes

2024-02-22 01:15 UTC, lewijacn requested changes
Thanks for cleaning this up! A few additional minor things we should do:
* Remove the analytics options from the `default-values.json`
* Add the otel collector enabled option to the `default-values.json`
* Remove the `accessAnalyticsDashboard.sh` file

2024-02-22 01:15 UTC, lewijacn commented on deployment/cdk/opensearch-service-migration/lib/stack-composer.ts
> -        const migrationAnalyticsServiceEnabled = this.getContextForType('migrationAnalyticsServiceEnabled', 'boolean', defaultValues, contextJSON)
We have an additional section in the `options.md`  file with these options, can you remove that specific section as well

2024-02-22 01:15 UTC, lewijacn commented on deployment/cdk/opensearch-service-migration/test/stack-composer-ordering.test.ts
> -        TrafficReplayerStack, KafkaBrokerStack, KafkaZookeeperStack, MigrationAnalyticsStack]
Seems like we should replace with OtelCollectorStack right?

2024-02-22 01:15 UTC, lewijacn commented on test/awsE2ESolutionSetup.sh
> +  otel_sg_id=$(aws ssm get-parameter --name "/migration/$deploy_stage/default/
Looks like this line got cut off from what I can tell

2024-02-22 21:04 UTC, lewijacn approved these changes

2024-03-07 15:49 UTC, merged